---
# Varnish角色的处理器

- name: restart varnish
  systemd:
    name: varnish
    state: restarted
  become: true

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: true

- name: restart varnishncsa
  systemd:
    name: varnishncsa
    state: restarted
  become: true 