---
# LEMP服务器主机清单
all:
  children:
    lemp_servers:
      hosts:
        # 本地安装配置
        localhost:
          ansible_connection: local
          hostname: lemp-server    # 主机名
    # 可以根据需要添加更多服务器组
    # web_servers:
    #   hosts:
    #     web1:
    #       ansible_host: 192.168.1.10
    #     web2:
    #       ansible_host: 192.168.1.11 