---
# Nginx 角色默认变量

# Nginx版本
nginx_version: "1.27"

# 基础设置
nginx_worker_processes: "auto"
nginx_worker_connections: 1024
nginx_client_max_body_size: "64m"
nginx_server_tokens: "off"

# ModSecurity配置
nginx_install_modsecurity: true  # 是否安装ModSecurity
nginx_modsecurity_rules_file: "/etc/nginx/modsecurity/modsecurity.conf"

# 默认站点配置
nginx_default_site_enabled: true
nginx_default_site_root: "/var/www/html"
nginx_default_site_name: "default"

# SSL/TLS 配置
nginx_ssl_protocols: "TLSv1.2 TLSv1.3"
nginx_ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
nginx_ssl_prefer_server_ciphers: "off"
nginx_ssl_session_cache: "shared:SSL:10m"
nginx_ssl_session_timeout: "1h"
nginx_ssl_session_tickets: "off"
nginx_ssl_stapling: "on"
nginx_ssl_stapling_verify: "on"

# 缓存和Gzip设置
nginx_gzip_enabled: true
nginx_gzip_comp_level: 5
nginx_gzip_types: "text/plain text/css text/xml text/javascript application/x-javascript application/json application/xml application/xml+rss"

# 日志设置
nginx_access_log: "/var/log/nginx/access.log"
nginx_error_log: "/var/log/nginx/error.log"
nginx_log_format: |
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"' 