---
# Valkey (Redis) 角色默认变量

# 版本配置
valkey_version: "8"

# 服务配置
valkey_port: 6379
valkey_bind_interface: "127.0.0.1"
valkey_unixsocket: "/var/run/valkey/valkey.sock"
valkey_unixsocketperm: "775"

# 安全配置
valkey_password: ""  # 为空表示不需要密码
valkey_supervised: "systemd"
valkey_daemonize: "no"

# 性能配置
valkey_maxclients: 10000
valkey_maxmemory: "128mb"
valkey_maxmemory_policy: "allkeys-lru"
valkey_tcp_backlog: 511
valkey_tcp_keepalive: 300
valkey_databases: 16

# 持久化配置
valkey_save:
  - "900 1"
  - "300 10"
  - "60 10000"
valkey_appendonly: "yes"
valkey_appendfsync: "everysec"

# 日志配置
valkey_loglevel: "notice"
valkey_logfile: "/var/log/valkey/valkey.log" 