---
# Nginx 处理器

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
  listen: "restart nginx"

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  listen: "reload nginx" 